### ISSUE TITLE
Use HEAD request to make the process quicker

### ISSUE THREAD

**Issue by fenglish** [Financial-Times/runbook.md#153]
To check whether the `systemCode` exists or not, we are making a call to biz-ops api on #150 . However biz-ops api doesn't allow `HEAD` request at the moment, once it accepts the requests we need to change [here](https://github.com/Financial-Times/runbook.md/blob/10191937e07a875bbc08088f2cc2762b59165691/lambdas/ingester/src/lib/biz-ops-client.js#L35)

**Comment by wheresrhys** [comment]
done
