### ISSUE TITLE
Multiple lines of description at the start of the runbook.md get truncated

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/runbook.md#62]
The intention of the Description field is to provide a one-paragraph summary of the system.  At the moment, entering multiple lines in a runbook.md introduction/description block result in only the first line being imported, with the other lines being dropped.

Either the multiple lines should generate a validation error, or the multiple lines should be combined into one line.

**Comment by wheresrhys** [comment]
I _think_ this is now fixed so it imports it all. SOS also penalises multiline descriptions
