### ISSUE TITLE
Links in the runbook.md description area are block-styled with large margins

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/runbook.md#63]
If a runbook.md introduction/description contains a markdown link, that markdown link is moved to its own paragraph, breaking up the flow of text and making sentences unreadable.

These should probably not be wrapped in a paragraph unless the entire content of the description is a link. (Or not at all!)

Automatically generated inline links (for example ft.com) are styled correctly.

**Comment by wheresrhys** [comment]
Fixed about a month ago. Was an interesting bug https://github.com/Financial-Times/treecreeper/pull/149
