### ISSUE TITLE
Multiple runbook.md in one repository

### ISSUE THREAD

**Issue by OttlikG** [Financial-Times/runbook.md#68]
At FT we have services which has systemCodes and runbook record although they not managed under GitHub.
At the moment we only support GitHub as the primary place of storing runbook.md files.
Due to the fact we want to edit the runbook of services not stored in github we offered a solution where we can store multiple runbook in one repository with a specific format.
`runbook-{system-code}.md`
This would be applicable on the following services:
- databases (elasticsearch, dynamoDb)
- thirdparty services (pingdom, heroku, aws)

One repo already using this convention: https://github.com/Financial-Times/next-url-management-service/pull/133

**Comment by doramatadora** [comment]
Supported as of https://github.com/Financial-Times/runbook.md/releases/tag/v38
